### ISSUE TITLE
Include Buekenhout-Metz and Buekenhout-Tits unitals in package

### ISSUE THREAD

**Issue by nagygp** [nagygp/UnitalSZ#7]
Buekenhout-Metz and Buekenhout-Tits unitals are already implemented. Include them in the package together with a command

`AllBuekenhoutMetzAbstractUnitalParameters(q)`

**Comment by davidmezofi** [comment]
Inclusion done in pull request #10

**Comment by nagygp** [comment]
This is fine so far. `AllBuekenhoutMetzAbstractUnitalParameters` needs more work. 
By now, we have parameters giving isomorphic unitals. 
The list of parameters must be such that up to isomorphism, one unital occurs exactly once.
This is explained in [S. Barwick G. Ebert. Unitals in Projective Planes. Springer-Verlag, 2008], page 72, formula (4.3). By a remark on page 83, the same formula holds for q even.

**Comment by davidmezofi** [comment]
A proposed patch is included in #11.
It runs quite fast for small `q`-s: The embedded `ForAny`-s method was incredibly slow compared to the method in the pull request.
The number of the resulting parameters seems to be good according to Theorems 4.14 (p. 73) and 4.25 (p. 81). The length of the list is always smaller by 1 as the theorems state since we omit the case, which yields the classical unital.

**Comment by nagygp** [comment]
Great, thanks.
